# Generated by Django 2.0.7 on 2018-07-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Загільна вартість всієї покупки')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзини',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('cart_item_total_price', models.PositiveIntegerField(default=0, verbose_name='Загальна вартість')),
            ],
            options={
                'verbose_name': 'Елемент корзини',
                'verbose_name_plural': 'Елементи корзини',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, verbose_name='Назва Товару')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Ціна')),
                ('text', models.TextField(default=None, verbose_name='Опис товару')),
                ('image', models.ImageField(default=None, upload_to='product/images', verbose_name='Зображення продукту')),
                ('category', models.ForeignKey(on_delete=None, to='api.Category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(default=None, on_delete=None, related_name='cart_item_product', to='api.Product', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, default=None, to='api.CartItem', verbose_name='Елементи корзини'),
        ),
    ]
