# Generated by Django 2.0.7 on 2018-07-18 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=None, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
