# Generated by Django 2.0.7 on 2018-07-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=200, verbose_name='Контактна особа')),
                ('email', models.CharField(default=None, max_length=200, verbose_name='email')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Загільна вартість покупки')),
                ('cart_items', models.ManyToManyField(blank=True, default=None, to='api.CartItem', verbose_name='Товари')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
