# Generated by Django 2.0.7 on 2018-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='desc',
            field=models.TextField(default=None, verbose_name='Додаткова інформація'),
        ),
    ]
